### ISSUE TITLE
brush doesn't work

### ISSUE THREAD

**Issue by yuti** [blackears/blenderNormalBrush#2] opened 2021-02-07 05:33 UTC
brush doesn't work
<img width="672" alt="brush doesn't work" src="https://user-images.githubusercontent.com/8939330/107137618-7ddf8480-6951-11eb-9c94-2f1f8d2e459f.png">

**Comment by blackears** [comment] 2021-02-07 09:49
I can't reproduce.  Which version of the plugin are you using?  I am doing my development and testing on Blender 2.91.0, so you might want to try that version.

**Comment by blackears** [comment] 2021-02-07 10:58
I had another look at it.  The error message that you're getting is the opposite of one I got before.  Your version of Blender is asking for a viewlayer instead of  a depsgraph, where as my version needs a depsgraph rather than a viewlayer.  Changing the code causes the addon to fail on my machine.

All I can suggest is that something strange is going on with your Blender installation.  You might want to try reinstalling.  Other people have installed this plugin and are not having problems with this.

**Comment by yuti** [comment] 2021-02-08 05:44
It works in 2.91.
Is it impossible to work in 2.9?

**Comment by blackears** [comment] 2021-02-08 16:06
I've made some changes.  The latest release should work on 2.90.

**Comment by yuti** [comment] 2021-02-08 18:22
thanks, And is the symmetry function possible?

**Comment by blackears** [comment] 2021-02-09 03:42
I've made a new release.  Symmetry is included in v1.1.4.

**Comment by blackears** [comment] 2021-02-15 08:50
If the problem has been resolved, please let me know so that I may close this issue.

**Comment by yuti** [comment] 2021-02-21 11:52
![brush](https://user-images.githubusercontent.com/8939330/108624185-92aa3500-7486-11eb-86ce-8582b248a1e9.gif)
The brush appears and the error message is normal, but it does not work.

**Comment by blackears** [comment] 2021-02-22 00:10
What are you doing after you press the Start Normal Tool button?  What happens when you click and the cursor over the model?  Do you see the pink circle of the cursor?  Do the normals change direction when you click and drag?  Are you doing this in Fixed mode?

If you still can't get it to work, please post a .blend file that demonstrates the issue and tell me specifically what steps you are taking and what you are expecting the tool to do - it would help me debug the issue.

Also, would you be able to post an image with the normal lengths longer so I can seen them more easily?

**Comment by blackears** [comment] 2021-02-22 06:21
I just reloaded the webpage - I didn't realize it was an animated gif you posted.  All I was seeing was the last frame.

That's very strange behavior you're having.  Are you still using Blender 2.90?  Have you tried using the latest Blender?  Would you be able to post a .blend file that demonstrates the problem?

**Comment by blackears** [comment] 2021-03-26 00:40
I'm closing this because I can't reproduce and no one else seems to be having this issue. Please reopen if you can provide a reproducible test case.

**Closed by blackears** 2021-03-26 00:40 UTC
